import { Filter, Search, SlidersHorizontal } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { listInvestigations } from "../api/client";
import type { Investigation } from "../api/types";
import { Badge } from "../components/Badge";
import { SectionPanel } from "../components/SectionPanel";
import { priorityClass } from "../utils/status";

export function History() {
  const [query, setQuery] = useState("");
  const [status, setStatus] = useState("All");
  const [rows, setRows] = useState<Investigation[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  useEffect(() => {
    async function loadHistory() {
      setLoading(true);
      setError("");
      try {
        setRows(await listInvestigations());
      } catch (err) {
        setError(err instanceof Error ? err.message : "Unable to load investigation history.");
      } finally {
        setLoading(false);
      }
    }

    void loadHistory();
  }, []);

  const filteredRows = useMemo(() => {
    return rows.filter((item) => {
      const matchesQuery = `${item.id} ${item.customerId} ${item.fieldName} ${item.issueDescription} ${item.analysis.summary}`.toLowerCase().includes(query.toLowerCase());
      const matchesStatus = status === "All" || item.status === status;
      return matchesQuery && matchesStatus;
    });
  }, [query, rows, status]);

  return (
    <div className="space-y-6">
      <div className="flex flex-wrap items-end justify-between gap-4">
        <div>
          <p className="text-sm font-semibold uppercase tracking-[0.24em] text-pink-300/80">Investigation archive</p>
          <h1 className="mt-2 text-3xl font-bold tracking-tight text-white sm:text-4xl">Investigation History</h1>
          <p className="mt-3 max-w-2xl text-sm leading-6 text-slate-400">
            Review SQL-based RCA records generated by the backend.
          </p>
        </div>
        <button className="flex items-center gap-2 rounded-2xl border border-white/10 bg-white/5 px-4 py-3 text-sm font-semibold text-slate-200 transition hover:border-pink-300/30 hover:text-pink-100">
          <SlidersHorizontal className="h-4 w-4" />
          Configure Columns
        </button>
      </div>

      <SectionPanel title="RCA Records" eyebrow="Search and filter" action={<Filter className="h-5 w-5 text-pink-200" />}>
        <div className="mb-5 grid gap-3 md:grid-cols-[1fr_220px]">
          <label className="flex items-center gap-3 rounded-2xl border border-white/10 bg-slate-950/45 px-4 py-3 transition focus-within:border-pink-300/50">
            <Search className="h-5 w-5 text-pink-200" />
            <input
              value={query}
              onChange={(event) => setQuery(event.target.value)}
              className="min-w-0 flex-1 bg-transparent text-sm text-slate-100 outline-none placeholder:text-slate-600"
              placeholder="Search ID, customer, issue, RCA result..."
            />
          </label>
          <select
            value={status}
            onChange={(event) => setStatus(event.target.value)}
            className="rounded-2xl border border-white/10 bg-slate-950/45 px-4 py-3 text-sm font-semibold text-slate-100 outline-none transition focus:border-pink-300/50"
          >
            <option>All</option>
            <option>Analyzed</option>
          </select>
        </div>

        {error ? <div className="mb-5 rounded-2xl border border-rose-300/25 bg-rose-400/10 px-4 py-3 text-sm text-rose-100">{error}</div> : null}

        <div className="overflow-x-auto">
          <table className="w-full min-w-[880px] text-left text-sm">
            <thead>
              <tr className="border-b border-white/10 text-xs uppercase tracking-[0.18em] text-slate-500">
                <th className="pb-3 font-semibold">Investigation ID</th>
                <th className="pb-3 font-semibold">Customer ID</th>
                <th className="pb-3 font-semibold">Issue Type</th>
                <th className="pb-3 font-semibold">Status</th>
                <th className="pb-3 font-semibold">Priority</th>
                <th className="pb-3 font-semibold">Created Date</th>
                <th className="pb-3 font-semibold">RCA Result</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-white/10">
              {filteredRows.map((item) => (
                <tr key={item.id} className="transition hover:bg-white/5">
                  <td className="py-4 font-semibold text-pink-100">
                    <Link to={`/result/${item.id}`} className="hover:text-pink-200">
                      {item.id}
                    </Link>
                  </td>
                  <td className="py-4 text-slate-300">{item.customerId || "Not provided"}</td>
                  <td className="py-4 text-slate-300">{item.fieldName || "SQL issue"}</td>
                  <td className="py-4">
                    <Badge>{item.status}</Badge>
                  </td>
                  <td className="py-4">
                      <span className={`inline-flex rounded-full border px-2.5 py-1 text-xs font-semibold ${priorityClass(item.priority)}`}>{item.priority}</span>
                  </td>
                  <td className="py-4 text-slate-300">{new Date(item.createdAt).toLocaleDateString()}</td>
                  <td className="max-w-[320px] truncate py-4 font-medium text-white">{item.analysis.summary}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        {loading ? (
          <div className="mt-6 rounded-2xl border border-slate-700 p-8 text-center text-sm text-slate-400">
            Loading investigations...
          </div>
        ) : null}

        {!loading && filteredRows.length === 0 ? (
          <div className="mt-6 rounded-2xl border border-dashed border-slate-700 p-8 text-center text-sm text-slate-400">
            No backend investigations match the current filters.
          </div>
        ) : null}
      </SectionPanel>
    </div>
  );
}
